spring: # be carefull during editing 
  config:
    import: optional:file:.env[.properties] # go to root of project 
  application:
    name: ${SPRING_APPLICATION_NAME:main} # optional no spring app name, take 'main' 
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.xml
  datasource:
    url: jdbc:${DBMS}://${HOST}:${PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: ${DRIVE_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      platform: ${DB_PLATFORM}